### ISSUE TITLE
Docs: README.md 작성하기

### ISSUE THREAD

**Issue by HyunJinNo** [TripInfoWeb/solitour-frontend#413]
## ❓ 어떤 기능인가요?

- README.md에 프로젝트 내용을 작성합니다.

## 📝 기능 설명

- README.md에 서비스 소개, 주요 기능, 아키텍처, 기술 스택 등 프로젝트 전반적인 내용을 작성합니다.

## ✅ TODO

구현해야 하는 기능에 대해 체크리스트를 작성해 주세요.

- [ ] 서비스 소개 작성
- [ ] 주요 기능 작성
- [ ] 아키텍처 작성
- [ ] 기술 스택 작성
- [ ] 팀원 소개 작성
